name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 2 hours
    - cron: "0 */1 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.3.1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          ### content
          SHOW_TITLE: true # optional
          SECTION_NAME: waka # optional
          CODE_LANG: rust # optional
          TIME_RANGE: last_30_days # optional
          LANG_COUNT: 5 # optional
          SHOW_TIME: true # optional
          SHOW_TOTAL: true # optional
          SHOW_MASKED_TIME: false # optional
          STOP_AT_OTHER: false # optional
          IGNORED_LANGUAGES: Binary YAML JSON TOML # optional
          
